= Professionelle Softwareentwicklung: Woche 1 
:icons: font
:icon-set: fa
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:experimental:

== Hinweise zu Lernvideos

Auch wenn es verführerisch sein mag, die Videos sind nicht gedacht um nebenher beim Kochen konsumiert zu werden. Sie sollten sich unbedingt die Zeit nehmen, die Inhalte genau nachzuvollziehen und aktiv zu erarbeiten. Um Ihnen bei der Bearbeitung zu helfen, gibt es zu jedem Video Fragen und Aufgaben, die Sie beantworten bzw. bearbeiten sollen. Diese Fragen und Aufgaben sind nur ein Startpunkt. Es ist wichtig, dass Sie sich aktiv mit den Inhalten auseinandersetzen. 

TIP: Meine Videos kann man auch auf 1.5 oder 2-facher Geschwindigkeit noch gut anschauen.

== Aufgabe 1: Begrüßung und Organisatorisches 

Schauen Sie sich das https://youtu.be/ad_540wfkrs[Begrüßungsvideo] und das Video zu den https://youtu.be/k6fRU8MY-cg[Lernzielen] der Veranstaltung an. 

*Leitfragen/Aufgaben:*

* Wann findet die Klausur statt?
* Wie viele der praktischen Übung müssen Sie erfolgreich absolvieren, um die Klausur mitschreiben zu dürfen?
* Welche Teile der Wochenblätter, Übungen und praktischen Übungen sind Bestandteil der Klausur?