= Professionelle Softwareentwicklung: Woche 1 
:icons: font
:icon-set: fa
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:experimental:

== Hinweise zu Lernvideos

Auch wenn es verführerisch sein mag, die Videos sind nicht gedacht um nebenher beim Kochen konsumiert zu werden. Sie sollten sich unbedingt die Zeit nehmen, die Inhalte genau nachzuvollziehen und aktiv zu erarbeiten. Um Ihnen bei der Bearbeitung zu helfen, gibt es zu jedem Video Fragen und Aufgaben, die Sie beantworten bzw. bearbeiten sollen. Diese Fragen und Aufgaben sind nur ein Startpunkt. Es ist wichtig, dass Sie sich aktiv mit den Inhalten auseinandersetzen. 

TIP: Meine Videos kann man auch auf 1.5 oder 2-facher Geschwindigkeit noch gut anschauen.

== Aufgabe 1: Begrüßung und Organisatorisches 

Schauen Sie sich das https://youtu.be/ad_540wfkrs[Begrüßungsvideo] und das Video zu den https://youtu.be/k6fRU8MY-cg[Lernzielen] der Veranstaltung an. 

Wen Sie es noch nicht gesehen haben, schauen Sie sich das https://youtu.be/X583zc8e0b0[Organisationsvideo] an und lesen Sie das https://github.com/hhu-propra1/Organisation/blob/main/organisatorisches.adoc[Organisationsdokument].

*Leitfragen/Aufgaben:*

* Wann findet die Klausur statt?
* Wie viele der praktischen Übung müssen Sie erfolgreich absolvieren, um die Klausur mitschreiben zu dürfen?
* Welche Teile der Wochenblätter, Übungen und praktischen Übungen sind Bestandteil der Klausur?
* Wie ist die Mailadresse, an die Sie sich wenden können, wenn Sie wegen einer Krankheit nicht an einer praktischen Übung teilnehmen können?
* Wie bekommen Sie Hilfe zu fachlichen Themen?
* Welche Deadlines gibt es?

*Zusatzmaterial:*

Falls Sie wissen wollen, wie Sie Ihren Lernerfolg optimieren können oder Probleme mit Prokrastination haben, sind hier zwei Videos, die vielleicht etwas Hilfestellung geben können:

* Video zum Thema https://www.youtube.com/watch?v=idEKH9O5xWs[gehirngerechtes Arbeiten]
* TED Talk von Tim Urban über https://youtu.be/arj7oStGLkU[Prokrastination] 

*SEAcon:*

Am 21. und 22.04.2021 findet die https://www.sea-con.de/seacon2021.html[SEAcon] Onlinekonferenz zum Thema Software-Engineering und Architektur statt. Viele der Themen passen ganz gut zu den Inhalten der Veranstaltungen des Programmierpraktikums. Wenn Sie Lust haben, sich das einmal anzuschauen, können Sie mit dem Code `SEACONdigi-Studis` dort kostenlos teilnehmen. Wählen Sie die "reguläre Teilnahme" aus und geben Sie den Code in dem Feld "SEACON digital Vorteilscode" ein. Sobald Sie das Eingabefeld für den Code verlassen, sollte dort stehen "Dieser Vorteilscode gewährt Ihnen einen Rabatt von 100% auf den regulären Ticketpreis."



== Aufgabe 2: Was ist eigentlich das Problem?

Im Praktikum werden wir uns mit der Fragestellung befassen, wie wir Software entwickeln, wenn ein sehr kleines Programm nicht mehr ausreicht und die Problemstellung komplex ist. 

Schauen Sie sich dazu dieses Video zum Thema https://youtu.be/ON276AlEGLM[Probleme der Softwareentwicklung] an. 

Ein wesentlicher Aspekt bei großen Systemen ist die Wartbarkeit. Wartbarkeit ist eines der Qualitätsziele (in der Literatur oft auch als nichtfunktionale Anforderungen bezeichnet), die in der ISO 25010 beschrieben werden. 

* Schauen Sie sich das Video zu https://youtu.be/pqsTCUZVTa0[Qualitätszielen in der ISO 25010] an. 

* Lesen Sie die sehr kurzen https://iso25000.com/index.php/en/iso-25000-standards/iso-25010?start=0[Definitionen] der einzelnen Begriffe durch.

* Lesen Sie die Seiten 56 bis 60 aus https://katalog.ulb.hhu.de/Record/002508972[Effektive Software-Architekturen: Ein praktischer Leitfaden] von Gernot Starke. Da das Buch von Starke von 2011 ist, bezieht es sich überwiegend auf die Norm ISO 9126, die ein Vorgänger von ISO 25010 ist. Die Unterschiede zwischen den beiden Normen sind relativ klein. Beispielsweise wurde das Thema Sicherheit, das in ISO 9126 ein Unterpunkt der Funktionalität ist, in der ISO 25010 zu einem eigenen Hauptpunkt mit Unterpunkten hochgestuft.  
+
NOTE: Sie müssen im VPN der Universität sein, um auf das Buch zugreifen zu können. Die Einrichtung des VPN ist unter https://wiki.hhu.de/display/OPENVPN/OpenVPN[https://wiki.hhu.de/display/OPENVPN/OpenVPN] beschrieben. 


*Leitfragen/Aufgaben:*

* Was ist der Zusammenhang zwischen Größe eines Softwareprojektes und der Erfolgsrate bei der Umsetzung? Wie können wir die Erfolgschancen verbessern?

* Die Einführung einer Software kann einen Effekt haben, der sich auf Arbeitsabläufe auswirkt, die dann wieder einen Effekt auf die Anforderungen an die Software haben. Überlegen Sie sich, wie Sie die Softwareentwicklung gestalten könnten, um diesen dynamischen Prozess nicht zu behindern oder vielleicht sogar positiv zu unterstützen.  

* Wir haben gesehen, dass sich Fehler oft am Anfang der Entwicklung einschleichen und erst spät bemerkt werden. Überlegen Sie sich, wie Sie die Situation verbessern können. Vergleichen Sie die Antwort auf diese Frage mit der Antwort auf die Vorgängerfrage. 

* Am Anfang jeden Semesters benötigen wir im Programmierpraktikum eine Zuordnung der Benutzerkennungen auf GitHub zu den entsprechenden Universitätskennungen. Wir verwenden dazu eine Webanwendung. Welches sind Ihrer Ansicht nach die wichtigsten Qualitätsziele (auf der genaueren Detailstufe der Ziele), die die Software erfüllen sollte? Begründen Sie die Wahl.

* In dem Einführungsvideo wurde als Beispiel für Ziele, die im Widerspruch stehen, Zeitverhalten und Koexistenz genannt. Es gibt aber auch Ziele, die sich positiv aufeinander auswirken. Finden Sie ein Paar von Zielen, die sich positiv beeinflussen. Begründen Sie, warum das so ist. 

* Die Definition von Authenticity ist "Degree to which the identity of a subject or resource can be proved to be the one claimed.". Überlegen Sie sich aus Ihrem Alltag im Umgang mit Webanwendungen, welche Möglichkeiten es gibt, um die Authenticity einer Webanwendung zu verbessern. 


*Zusatzmaterial:*

* Eine Sammlung von https://github.com/arc42/quality-requirements/releases/download/v0.7.6/index.pdf[Beispielen für Qualitätsanforderungen]

* https://youtu.be/O3bO_3h0QtU[Dein Weg zu besseren Anforderungen], ein sehr lohnenswerter und unterhaltsamer Vortrag von Gernot Starke zum Thema Anforderungen und Qualität